_target_: src.logger.CometMLWriter
project_name: "HiFi-GAN"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["g_loss", "g_adv_loss", "g_feat_loss", "g_mel_loss", "d_loss", "d_mpd_loss", "d_msd_loss"]
log_checkpoints: True
id_length: 32
